services:
    #core:
    #    build: .
    #    environment:
    #    - MYSQL_HOST=mysql
    #    - MYSQL_ROOT_PASSWORD=beeblebrox
    #    - MYSQL_USER=test
    #    - MYSQL_PASSWORD=zaphod
    #    restart: always
    #    links:
    #    - mysql

    tlserver:
        build:
            dockerfile: ./config/tlserver/Dockerfile
            context: .
            args:
            - GOFLAGS
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_PASSWORD=zaphod
        restart: always
        ports:
        - '8090:8090'
        - '8091:8091'
        expose:
        - '8090'
        - '8091'
        depends_on:
        - mysql

    tlsigner:
        build:
            context: .
            dockerfile: ./config/tlsigner/Dockerfile
            args:
            - GOFLAGS
        restart: always
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_PASSWORD=zaphod
        ports:
        - '8092:8091'
        depends_on:
        - mysql


    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=zaphod
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - data_volume:/data/db

    slate:
        image: golang:1.11
        restart: always

volumes:
    data_volume:

version: '3'
