services:
    core:
        build:
            context: .
            dockerfile: ./config/core/Dockerfile
            args:
            - GOFLAGS
        restart: always
        links:
        - mysql

    tlserver:
        build:
            context: .
            dockerfile: ./config/tlserver/Dockerfile
            args:
            - GOFLAGS
        restart: always
        ports:
        - '8090:8090'
        - '8091:8091'
        expose:
        - '8090'
        - '8091'
        depends_on:
        - mysql

    tlsigner:
        build:
            context: .
            dockerfile: ./config/tlsigner/Dockerfile
            args:
            - GOFLAGS
        restart: always
        ports:
        - '8092:8091'
        depends_on:
        - mysql


    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_DATABASE=cttest
        - MYSQL_USER=test
        - MYSQL_PASSWORD=zaphod
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - data_volume:/data/db


volumes:
    data_volume:

version: '3'
